### ISSUE TITLE
match_opcode miss some opcode

### ISSUE THREAD

**Issue by buhe** [trmckay/lib-rv32#12]
Hi, awesome project!

But, match_opcode miss some common opcode, like"li , mv"

**Comment by buhe** [comment]
Sorry for : https://github.com/riscv-non-isa/riscv-asm-manual/blob/master/riscv-asm.md

look "li..." is a pseudo instructions

**Comment by trmckay** [comment]
Thanks for the interest! Haven't worked on this in a while but it's not "abandoned" per se. If you see anything else missing just open an issue.

**Comment by buhe** [comment]
thanks, i open a pr,have a look when you have time~
