### ISSUE TITLE
Maybe support pseudo instructions?

### ISSUE THREAD

**Issue by buhe** [trmckay/lib-rv32#14]
any good ideas or any suggestion～

**Comment by buhe** [comment]
background: I coding a toy complier (https://github.com/buhe/rust_cc_study) use rust. Use lib-rv32 gen bin code

**Comment by trmckay** [comment]
Is your compiler generating psuedo-instructions? Some psuedo-instructions are already supported. Still, I'm not sure this assembler is fit for a compiler. It's _very_ experimental and really only exists so I could run programs for a web-app demo. You would probably be better off using the [riscv-gnu-toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain).

This assembler really just needs a full rewrite with an actual lexer/parser.

**Comment by buhe** [comment]
thanks
